---
repos:
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.21.0
  hooks:
  - id: yamllint
    args: [--format, parsable, --strict]

- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.0.11
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --colons, --width, '150']

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: pretty-format-json
    args: [--no-sort-keys, --indent 2]

- repo: https://github.com/pycqa/pylint
  rev: pylint-2.6.0
  hooks:
  - id: pylint
    args: [--errors-only]

- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3.7.6
